# Data Analysis with Python

## Numpy

## freeCodeCamp.org YouTube

In [1]:
# some data about rainfall

w1, w2, w3 = 0.3, 0.2, 0.5

kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

weights = [w1,w2,w3]

# function to calculate crop yield from above data
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

crop_yield(kanto, weights)

56.8

In [2]:
import numpy as np

In [4]:
# create numpy arrays

kanto = np.array([73,67,43])
weights = np.array([0.3,0.2,0.5])

In [5]:
type(kanto)

numpy.ndarray

In [6]:
# we can now compute dot products with numpy arrays

np.dot(kanto, weights)

56.8

In [7]:
# or we can use element wise multiplication
kanto * weights

array([21.9, 13.4, 21.5])

In [8]:
sum(kanto*weights)

56.8

In [9]:
# we can also put all the data into a matrix

climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])

# dimensions of array
climate_data.shape

(5, 3)

In [10]:
# check datatype
weights.dtype

dtype('float64')

In [11]:
climate_data.dtype

dtype('int64')

In [13]:
# matrix multiplication
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [14]:
# @ symbol for matrix multiplication
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [16]:
# retrieve a txt file online
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

# read into python with numpy genfromtxt function
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [17]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [18]:
climate_data.shape

(10000, 3)

In [19]:
yields = climate_data @ weights

In [20]:
yields.shape

(10000,)

In [21]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [22]:
# add the yields as a new column in our matrix
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [23]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [24]:
# save our results as a file
np.savetxt('climate_results.txt',
           climate_results,
           fmt='%.2f',
           header='temp,rainfall,humidity,yield',
           comments='')

In [25]:
# adding and subtracting with arrays

arr2 = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])

arr2 + 2

array([[ 75,  69,  45],
       [ 93,  90,  66],
       [ 89, 136,  60],
       [104,  45,  39],
       [ 71,  98,  72]])

In [26]:
arr2 + np.array([1, 10, 100])

array([[ 74,  77, 143],
       [ 92,  98, 164],
       [ 88, 144, 158],
       [103,  53, 137],
       [ 70, 106, 170]])

In [28]:
arr_b = np.array([1, 10, 100]) == np.array([1, 10, 10])
arr_b

array([ True,  True, False])

In [31]:
any(arr_b)

True

In [32]:
sum(arr_b)

2

In [36]:
# select elements of an array
arr2[0, 0]

73

In [37]:
# first row
arr2[0, ]

array([73, 67, 43])

In [39]:
# first element of each row
arr2[0:, 0]

array([ 73,  91,  87, 102,  69])

In [43]:
# first two rows
arr2[:2, 0:]

array([[73, 67, 43],
       [91, 88, 64]])

In [44]:
arr2[0]

array([73, 67, 43])

In [46]:
# array of zeros
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# array of random numbers
np.random.rand(3,3)

array([[0.80882387, 0.09273424, 0.04173493],
       [0.41895872, 0.26038169, 0.07460066],
       [0.48927691, 0.31295967, 0.70907831]])

In [50]:
# change shape of array
# arange counts from 10 to 90 by 3
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])